--Autores: Jacobo Vargas, Kevin Payanene, Steven Morales
---------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.tipo_cliente(
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre VARCHAR,
    CONSTRAINT tipo_cliente_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.cliente (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cedula VARCHAR,
    nombre VARCHAR,
    apellido_uno VARCHAR,
    apellido_dos VARCHAR,
    fecha_nacimiento DATE,
    tipo_cliente_id INTEGER,
    CONSTRAINT cliente_pkey PRIMARY KEY (id),
    CONSTRAINT cliente_tipo_cliente_fk FOREIGN KEY (tipo_cliente_id)
    REFERENCES public.tipo_cliente (id) MATCH SIMPLE

    );