--Autores: Jacobo Vargas, Kevin Payanene, Steven Morales
---------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.sucursal (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ciudad VARCHAR,
    nombre VARCHAR,
    direccion VARCHAR,
    telefono VARCHAR,
    CONSTRAINT sucursal_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.cliente
    ADD COLUMN sucursal_id INTEGER,
    ADD CONSTRAINT sucursal_id_fk FOREIGN KEY (sucursal_id)
    REFERENCES public.sucursal (id) MATCH SIMPLE;


CREATE TABLE IF NOT EXISTS public.ventanilla (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    valor_base DOUBLE PRECISION,
    fecha_apertura DATE,
    fecha_cierre DATE,
    sucursal_id INTEGER,
    CONSTRAINT ventanilla_pkey PRIMARY KEY (id),
    CONSTRAINT sucursal_id_fk FOREIGN KEY (sucursal_id)
        REFERENCES public.sucursal (id) MATCH SIMPLE

);

CREATE TABLE IF NOT EXISTS public.producto (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cedula VARCHAR,
    nombre VARCHAR,
    tipo_producto VARCHAR,
    CONSTRAINT producto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cuenta (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    numero_cuenta INTEGER,
    fecha_creacion DATE,
    cliente_id INTEGER,
    producto_id INTEGER,
    CONSTRAINT cuenta_pkey PRIMARY KEY (id),
    CONSTRAINT cliente_id_fk FOREIGN KEY (cliente_id)
        REFERENCES public.cliente (id) MATCH SIMPLE,
    CONSTRAINT producto_id_fk FOREIGN KEY (producto_id)
        REFERENCES public.producto (id) MATCH SIMPLE
);

CREATE TABLE IF NOT EXISTS public.estado (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre VARCHAR,
    fecha_estado DATE,
    CONSTRAINT estado_pkey PRIMARY KEY (id)
);



