--Autores: Jacobo Vargas, Kevin Payanene, Steven Morales
---------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.solicitud (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fecha_solicitud DATE,
    valor DOUBLE PRECISION,
    moneda VARCHAR,
    cliente_id INTEGER,
    producto_id INTEGER,
    CONSTRAINT solicitud_pkey PRIMARY KEY (id),
    CONSTRAINT cliente_id_fk FOREIGN KEY (cliente_id)
        REFERENCES public.cliente (id) MATCH SIMPLE,
    CONSTRAINT producto_id_fk FOREIGN KEY (producto_id)
        REFERENCES public.producto (id) MATCH SIMPLE
);


CREATE TABLE IF NOT EXISTS public.empleado (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre VARCHAR,
    apellido_uno VARCHAR,
    apellido_dos VARCHAR,
    salario DOUBLE PRECISION,
    fecha_contratacion DATE,
    cargo VARCHAR,
    sucursal_id INTEGER,
    estado_id INTEGER,
    CONSTRAINT empleado_pkey PRIMARY KEY (id),
    CONSTRAINT sucursal_id_fk FOREIGN KEY (sucursal_id)
        REFERENCES public.sucursal (id) MATCH SIMPLE,
    CONSTRAINT estado_id_fk FOREIGN KEY (estado_id)
        REFERENCES public.estado (id) MATCH SIMPLE

);

CREATE TABLE IF NOT EXISTS public.tipo_transaccion (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre VARCHAR,
    CONSTRAINT tipo_transaccion_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transaccion (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    valor DOUBLE PRECISION,
    fecha_transaccion DATE,
    tipo_transaccion_id INTEGER,
    estado_id INTEGER,
    cuenta_id INTEGER,
    CONSTRAINT transaccion_pkey PRIMARY KEY (id),
    CONSTRAINT tipo_transaccion_id_fk FOREIGN KEY (tipo_transaccion_id)
        REFERENCES public.tipo_transaccion (id) MATCH SIMPLE,
    CONSTRAINT estado_id_fk FOREIGN KEY (estado_id)
        REFERENCES public.estado (id) MATCH SIMPLE,
    CONSTRAINT cuenta_id_fk FOREIGN KEY (cuenta_id)
        REFERENCES public.cuenta (id) MATCH SIMPLE
);

CREATE TABLE IF NOT EXISTS public.factura (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    formato VARCHAR,
    fecha DATE,
    valor DOUBLE PRECISION,
    transaccion_id INTEGER,
    CONSTRAINT factura_pkey PRIMARY KEY (id),
    CONSTRAINT transaccion_id_fk FOREIGN KEY (transaccion_id)
        REFERENCES public.transaccion (id) MATCH SIMPLE
);



